# Analisis de Datos del Censo Estatal.

Una vez los datos estan descargados. Procedemos con un analisis de los datos.

In [1]:
from vothmo.config import CENSO_DATA
import os

data_folders = os.listdir(CENSO_DATA)

files = {}

for folder in data_folders:
    fdr = CENSO_DATA / folder
    lfdr = os.listdir(fdr)
    folder_pth = fdr / lfdr[0]
    for file in os.listdir(folder_pth):
        files[file] = folder_pth / file

files

{'01_descripcioncampos_conteoscensales_prisionpreventiva2024.txt': PosixPath('/home/david/Documents/Repositories/academica/Votacion2026/data/Censos/DatosAbiertos_DECEyEC_ConteosCensales_PrisionPreventiva2024-1/DatosAbiertos_DECEyEC_ConteosCensales_PrisionPreventiva2024/01_descripcioncampos_conteoscensales_prisionpreventiva2024.txt'),
 'datosabiertos_deceyec_conteoscensales_prisionpreventiva2024.csv': PosixPath('/home/david/Documents/Repositories/academica/Votacion2026/data/Censos/DatosAbiertos_DECEyEC_ConteosCensales_PrisionPreventiva2024-1/DatosAbiertos_DECEyEC_ConteosCensales_PrisionPreventiva2024/datosabiertos_deceyec_conteoscensales_prisionpreventiva2024.csv'),
 '01_descripcioncampos_conteoscensales_votoanticipado2024.txt': PosixPath('/home/david/Documents/Repositories/academica/Votacion2026/data/Censos/DatosAbiertos_DECEyEC_ConteosCensales_VotoAnticipado2024/DatosAbiertos_DECEyEC_ConteosCensales_VotoAnticipado2024/01_descripcioncampos_conteoscensales_votoanticipado2024.txt'),
 'datosabiertos_deceyec_conteoscensales_votoanticipado2024.csv': PosixPath('/home/david/Documents/Repositories/academica/Votacion2026/data/Censos/DatosAbiertos_DECEyEC_ConteosCensales_VotoAnticipado2024/DatosAbiertos_DECEyEC_ConteosCensales_VotoAnticipado2024/datosabiertos_deceyec_conteoscensales_votoanticipado2024.csv'),
 '01_descripcioncampos_conteoscensales2009.txt': PosixPath('/home/david/Documents/Repositories/academica/Votacion2026/data/Censos/DatosAbiertos_DECEyEC_ConteosCensales2009/DatosAbiertos_DECEyEC_ConteosCensales2009/01_descripcioncampos_conteoscensales2009.txt'),
 'datosabiertos_deceyec_conteoscensales2009_ags.csv': PosixPath('/home/david/Documents/Repositories/academica/Votacion2026/data/Censos/DatosAbiertos_DECEyEC_ConteosCensales2009/DatosAbiertos_DECEyEC_ConteosCensales2009/datosabiertos_deceyec_conteoscensales2009_ags.csv'),
 'datosabiertos_deceyec_conteoscensales2009_bc.csv': PosixPath('/home/david/Documents/Repositories/academica/Votacion2026/data/Censos/DatosAbiertos_DECEyEC_ConteosCensales2009/DatosAbiertos_DECEyEC_ConteosCensales2009/datosabiertos_deceyec_conteoscensales2009_bc.csv'),
 'datosabiertos_deceyec_conteoscensales2009_bcs.csv': PosixPath('/home/david/Documents/Repositories/academica/Votacion2026/data/Censos/DatosAbiertos_DECEyEC_ConteosCensales2009/DatosAbiertos_DECEyEC_ConteosCensales2009/datosabiertos_deceyec_conteoscensales2009_bcs.csv'),
 'datosabiertos_deceyec_conteoscensales2009_camp.csv': PosixPath('/home/david/Documents/Repositories/academica/Votacion2026/data/Censos/DatosAbiertos_DECEyEC_ConteosCensales2009/DatosAbiertos_DECEyEC_ConteosCensales2009/datosabiertos_deceyec_conteoscensales2009_camp.csv'),
 'datosabiertos_deceyec_conteoscensales2009_cdmx.csv': PosixPath('/home/david/Documents/Repositories/academica/Votacion2026/data/Censos/DatosAbiertos_DECEyEC_ConteosCensales2009/DatosAbiertos_DECEyEC_ConteosCensales2009/datosabiertos_deceyec_conteoscensales2009_cdmx.csv'),
 'datosabiertos_deceyec_conteoscensales2009_chih.csv': PosixPath('/home/david/Documents/Repositories/academica/Votacion2026/data/Censos/DatosAbiertos_DECEyEC_ConteosCensales2009/DatosAbiertos_DECEyEC_ConteosCensales2009/datosabiertos_deceyec_conteoscensales2009_chih.csv'),
 'datosabiertos_deceyec_conteoscensales2009_chis.csv': PosixPath('/home/david/Documents/Repositories/academica/Votacion2026/data/Censos/DatosAbiertos_DECEyEC_ConteosCensales2009/DatosAbiertos_DECEyEC_ConteosCensales2009/datosabiertos_deceyec_conteoscensales2009_chis.csv'),
 'datosabiertos_deceyec_conteoscensales2009_coah.csv': PosixPath('/home/david/Documents/Repositories/academica/Votacion2026/data/Censos/DatosAbiertos_DECEyEC_ConteosCensales2009/DatosAbiertos_DECEyEC_ConteosCensales2009/datosabiertos_deceyec_conteoscensales2009_coah.csv'),
 'datosabiertos_deceyec_conteoscensales2009_col.csv': PosixPath('/home/david/Documents/Repositories/academica/Votacion2026/data/Censos/DatosAbiertos_DECEyEC_ConteosCensales2009/DatosAbiertos_DECEyEC_ConteosCensales2009/datosabiertos_deceyec_conteoscensales2009_col.csv'),
 'datosabiertos_deceyec_conteoscensales2009_dgo.csv': PosixPath('/home/david/Documents/Repositories/academica/Votacion2026/data/Censos/DatosAbiertos_DECEyEC_ConteosCensales2009/DatosAbiertos_DECEyEC_ConteosCensales2009/datosabiertos_deceyec_conteoscensales2009_dgo.csv'),
 'datosabiertos_deceyec_conteoscensales2009_gro.csv': PosixPath('/home/david/Documents/Repositories/academica/Votacion2026/data/Censos/DatosAbiertos_DECEyEC_ConteosCensales2009/DatosAbiertos_DECEyEC_ConteosCensales2009/datosabiertos_deceyec_conteoscensales2009_gro.csv'),
 'datosabiertos_deceyec_conteoscensales2009_gto.csv': PosixPath('/home/david/Documents/Repositories/academica/Votacion2026/data/Censos/DatosAbiertos_DECEyEC_ConteosCensales2009/DatosAbiertos_DECEyEC_ConteosCensales2009/datosabiertos_deceyec_conteoscensales2009_gto.csv'),
 'datosabiertos_deceyec_conteoscensales2009_hgo.csv': PosixPath('/home/david/Documents/Repositories/academica/Votacion2026/data/Censos/DatosAbiertos_DECEyEC_ConteosCensales2009/DatosAbiertos_DECEyEC_ConteosCensales2009/datosabiertos_deceyec_conteoscensales2009_hgo.csv'),
 'datosabiertos_deceyec_conteoscensales2009_jal.csv': PosixPath('/home/david/Documents/Repositories/academica/Votacion2026/data/Censos/DatosAbiertos_DECEyEC_ConteosCensales2009/DatosAbiertos_DECEyEC_ConteosCensales2009/datosabiertos_deceyec_conteoscensales2009_jal.csv'),
 'datosabiertos_deceyec_conteoscensales2009_mex.csv': PosixPath('/home/david/Documents/Repositories/academica/Votacion2026/data/Censos/DatosAbiertos_DECEyEC_ConteosCensales2009/DatosAbiertos_DECEyEC_ConteosCensales2009/datosabiertos_deceyec_conteoscensales2009_mex.csv'),
 'datosabiertos_deceyec_conteoscensales2009_mich.csv': PosixPath('/home/david/Documents/Repositories/academica/Votacion2026/data/Censos/DatosAbiertos_DECEyEC_ConteosCensales2009/DatosAbiertos_DECEyEC_ConteosCensales2009/datosabiertos_deceyec_conteoscensales2009_mich.csv'),
 'datosabiertos_deceyec_conteoscensales2009_mor.csv': PosixPath('/home/david/Documents/Repositories/academica/Votacion2026/data/Censos/DatosAbiertos_DECEyEC_ConteosCensales2009/DatosAbiertos_DECEyEC_ConteosCensales2009/datosabiertos_deceyec_conteoscensales2009_mor.csv'),
 'datosabiertos_deceyec_conteoscensales2009_nay.csv': PosixPath('/home/david/Documents/Repositories/academica/Votacion2026/data/Censos/DatosAbiertos_DECEyEC_ConteosCensales2009/DatosAbiertos_DECEyEC_ConteosCensales2009/datosabiertos_deceyec_conteoscensales2009_nay.csv'),
 'datosabiertos_deceyec_conteoscensales2009_nl.csv': PosixPath('/home/david/Documents/Repositories/academica/Votacion2026/data/Censos/DatosAbiertos_DECEyEC_ConteosCensales2009/DatosAbiertos_DECEyEC_ConteosCensales2009/datosabiertos_deceyec_conteoscensales2009_nl.csv'),
 'datosabiertos_deceyec_conteoscensales2009_oax.csv': PosixPath('/home/david/Documents/Repositories/academica/Votacion2026/data/Censos/DatosAbiertos_DECEyEC_ConteosCensales2009/DatosAbiertos_DECEyEC_ConteosCensales2009/datosabiertos_deceyec_conteoscensales2009_oax.csv'),
 'datosabiertos_deceyec_conteoscensales2009_pue.csv': PosixPath('/home/david/Documents/Repositories/academica/Votacion2026/data/Censos/DatosAbiertos_DECEyEC_ConteosCensales2009/DatosAbiertos_DECEyEC_ConteosCensales2009/datosabiertos_deceyec_conteoscensales2009_pue.csv'),
 'datosabiertos_deceyec_conteoscensales2009_qro.csv': PosixPath('/home/david/Documents/Repositories/academica/Votacion2026/data/Censos/DatosAbiertos_DECEyEC_ConteosCensales2009/DatosAbiertos_DECEyEC_ConteosCensales2009/datosabiertos_deceyec_conteoscensales2009_qro.csv'),
 'datosabiertos_deceyec_conteoscensales2009_qroo.csv': PosixPath('/home/david/Documents/Repositories/academica/Votacion2026/data/Censos/DatosAbiertos_DECEyEC_ConteosCensales2009/DatosAbiertos_DECEyEC_ConteosCensales2009/datosabiertos_deceyec_conteoscensales2009_qroo.csv'),
 'datosabiertos_deceyec_conteoscensales2009_sin.csv': PosixPath('/home/david/Documents/Repositories/academica/Votacion2026/data/Censos/DatosAbiertos_DECEyEC_ConteosCensales2009/DatosAbiertos_DECEyEC_ConteosCensales2009/datosabiertos_deceyec_conteoscensales2009_sin.csv'),
 'datosabiertos_deceyec_conteoscensales2009_slp.csv': PosixPath('/home/david/Documents/Repositories/academica/Votacion2026/data/Censos/DatosAbiertos_DECEyEC_ConteosCensales2009/DatosAbiertos_DECEyEC_ConteosCensales2009/datosabiertos_deceyec_conteoscensales2009_slp.csv'),
 'datosabiertos_deceyec_conteoscensales2009_son.csv': PosixPath('/home/david/Documents/Repositories/academica/Votacion2026/data/Censos/DatosAbiertos_DECEyEC_ConteosCensales2009/DatosAbiertos_DECEyEC_ConteosCensales2009/datosabiertos_deceyec_conteoscensales2009_son.csv'),
 'datosabiertos_deceyec_conteoscensales2009_tab.csv': PosixPath('/home/david/Documents/Repositories/academica/Votacion2026/data/Censos/DatosAbiertos_DECEyEC_ConteosCensales2009/DatosAbiertos_DECEyEC_ConteosCensales2009/datosabiertos_deceyec_conteoscensales2009_tab.csv'),
 'datosabiertos_deceyec_conteoscensales2009_tamps.csv': PosixPath('/home/david/Documents/Repositories/academica/Votacion2026/data/Censos/DatosAbiertos_DECEyEC_ConteosCensales2009/DatosAbiertos_DECEyEC_ConteosCensales2009/datosabiertos_deceyec_conteoscensales2009_tamps.csv'),
 'datosabiertos_deceyec_conteoscensales2009_tlax.csv': PosixPath('/home/david/Documents/Repositories/academica/Votacion2026/data/Censos/DatosAbiertos_DECEyEC_ConteosCensales2009/DatosAbiertos_DECEyEC_ConteosCensales2009/datosabiertos_deceyec_conteoscensales2009_tlax.csv'),
 'datosabiertos_deceyec_conteoscensales2009_ver.csv': PosixPath('/home/david/Documents/Repositories/academica/Votacion2026/data/Censos/DatosAbiertos_DECEyEC_ConteosCensales2009/DatosAbiertos_DECEyEC_ConteosCensales2009/datosabiertos_deceyec_conteoscensales2009_ver.csv'),
 'datosabiertos_deceyec_conteoscensales2009_yuc.csv': PosixPath('/home/david/Documents/Repositories/academica/Votacion2026/data/Censos/DatosAbiertos_DECEyEC_ConteosCensales2009/DatosAbiertos_DECEyEC_ConteosCensales2009/datosabiertos_deceyec_conteoscensales2009_yuc.csv'),
 'datosabiertos_deceyec_conteoscensales2009_zac.csv': PosixPath('/home/david/Documents/Repositories/academica/Votacion2026/data/Censos/DatosAbiertos_DECEyEC_ConteosCensales2009/DatosAbiertos_DECEyEC_ConteosCensales2009/datosabiertos_deceyec_conteoscensales2009_zac.csv'),
 '01_descripcioncampos_conteoscensales2012.txt': PosixPath('/home/david/Documents/Repositories/academica/Votacion2026/data/Censos/DatosAbiertos_DECEyEC_ConteosCensales2012/DatosAbiertos_DECEyEC_ConteosCensales2012/01_descripcioncampos_conteoscensales2012.txt'),
 'datosabiertos_deceyec_conteoscensales2012_ags.csv': PosixPath('/home/david/Documents/Repositories/academica/Votacion2026/data/Censos/DatosAbiertos_DECEyEC_ConteosCensales2012/DatosAbiertos_DECEyEC_ConteosCensales2012/datosabiertos_deceyec_conteoscensales2012_ags.csv'),
 'datosabiertos_deceyec_conteoscensales2012_bc.csv': PosixPath('/home/david/Documents/Repositories/academica/Votacion2026/data/Censos/DatosAbiertos_DECEyEC_ConteosCensales2012/DatosAbiertos_DECEyEC_ConteosCensales2012/datosabiertos_deceyec_conteoscensales2012_bc.csv'),
 'datosabiertos_deceyec_conteoscensales2012_bcs.csv': PosixPath('/home/david/Documents/Repositories/academica/Votacion2026/data/Censos/DatosAbiertos_DECEyEC_ConteosCensales2012/DatosAbiertos_DECEyEC_ConteosCensales2012/datosabiertos_deceyec_conteoscensales2012_bcs.csv'),
 'datosabiertos_deceyec_conteoscensales2012_camp.csv': PosixPath('/home/david/Documents/Repositories/academica/Votacion2026/data/Censos/DatosAbiertos_DECEyEC_ConteosCensales2012/DatosAbiertos_DECEyEC_ConteosCensales2012/datosabiertos_deceyec_conteoscensales2012_camp.csv'),
 'datosabiertos_deceyec_conteoscensales2012_cdmx.csv': PosixPath('/home/david/Documents/Repositories/academica/Votacion2026/data/Censos/DatosAbiertos_DECEyEC_ConteosCensales2012/DatosAbiertos_DECEyEC_ConteosCensales2012/datosabiertos_deceyec_conteoscensales2012_cdmx.csv'),
 'datosabiertos_deceyec_conteoscensales2012_chih.csv': PosixPath('/home/david/Documents/Repositories/academica/Votacion2026/data/Censos/DatosAbiertos_DECEyEC_ConteosCensales2012/DatosAbiertos_DECEyEC_ConteosCensales2012/datosabiertos_deceyec_conteoscensales2012_chih.csv'),
 'datosabiertos_deceyec_conteoscensales2012_chis.csv': PosixPath('/home/david/Documents/Repositories/academica/Votacion2026/data/Censos/DatosAbiertos_DECEyEC_ConteosCensales2012/DatosAbiertos_DECEyEC_ConteosCensales2012/datosabiertos_deceyec_conteoscensales2012_chis.csv'),
 'datosabiertos_deceyec_conteoscensales2012_coah.csv': PosixPath('/home/david/Documents/Repositories/academica/Votacion2026/data/Censos/DatosAbiertos_DECEyEC_ConteosCensales2012/DatosAbiertos_DECEyEC_ConteosCensales2012/datosabiertos_deceyec_conteoscensales2012_coah.csv'),
 'datosabiertos_deceyec_conteoscensales2012_col.csv': PosixPath('/home/david/Documents/Repositories/academica/Votacion2026/data/Censos/DatosAbiertos_DECEyEC_ConteosCensales2012/DatosAbiertos_DECEyEC_ConteosCensales2012/datosabiertos_deceyec_conteoscensales2012_col.csv'),
 'datosabiertos_deceyec_conteoscensales2012_dgo.csv': PosixPath('/home/david/Documents/Repositories/academica/Votacion2026/data/Censos/DatosAbiertos_DECEyEC_ConteosCensales2012/DatosAbiertos_DECEyEC_ConteosCensales2012/datosabiertos_deceyec_conteoscensales2012_dgo.csv'),
 'datosabiertos_deceyec_conteoscensales2012_gro.csv': PosixPath('/home/david/Documents/Repositories/academica/Votacion2026/data/Censos/DatosAbiertos_DECEyEC_ConteosCensales2012/DatosAbiertos_DECEyEC_ConteosCensales2012/datosabiertos_deceyec_conteoscensales2012_gro.csv'),
 'datosabiertos_deceyec_conteoscensales2012_gto.csv': PosixPath('/home/david/Documents/Repositories/academica/Votacion2026/data/Censos/DatosAbiertos_DECEyEC_ConteosCensales2012/DatosAbiertos_DECEyEC_ConteosCensales2012/datosabiertos_deceyec_conteoscensales2012_gto.csv'),
 'datosabiertos_deceyec_conteoscensales2012_hgo.csv': PosixPath('/home/david/Documents/Repositories/academica/Votacion2026/data/Censos/DatosAbiertos_DECEyEC_ConteosCensales2012/DatosAbiertos_DECEyEC_ConteosCensales2012/datosabiertos_deceyec_conteoscensales2012_hgo.csv'),
 'datosabiertos_deceyec_conteoscensales2012_jal.csv': PosixPath('/home/david/Documents/Repositories/academica/Votacion2026/data/Censos/DatosAbiertos_DECEyEC_ConteosCensales2012/DatosAbiertos_DECEyEC_ConteosCensales2012/datosabiertos_deceyec_conteoscensales2012_jal.csv'),
 'datosabiertos_deceyec_conteoscensales2012_mex.csv': PosixPath('/home/david/Documents/Repositories/academica/Votacion2026/data/Censos/DatosAbiertos_DECEyEC_ConteosCensales2012/DatosAbiertos_DECEyEC_ConteosCensales2012/datosabiertos_deceyec_conteoscensales2012_mex.csv'),
 'datosabiertos_deceyec_conteoscensales2012_mich.csv': PosixPath('/home/david/Documents/Repositories/academica/Votacion2026/data/Censos/DatosAbiertos_DECEyEC_ConteosCensales2012/DatosAbiertos_DECEyEC_ConteosCensales2012/datosabiertos_deceyec_conteoscensales2012_mich.csv'),
 'datosabiertos_deceyec_conteoscensales2012_mor.csv': PosixPath('/home/david/Documents/Repositories/academica/Votacion2026/data/Censos/DatosAbiertos_DECEyEC_ConteosCensales2012/DatosAbiertos_DECEyEC_ConteosCensales2012/datosabiertos_deceyec_conteoscensales2012_mor.csv'),
 'datosabiertos_deceyec_conteoscensales2012_nay.csv': PosixPath('/home/david/Documents/Repositories/academica/Votacion2026/data/Censos/DatosAbiertos_DECEyEC_ConteosCensales2012/DatosAbiertos_DECEyEC_ConteosCensales2012/datosabiertos_deceyec_conteoscensales2012_nay.csv'),
 'datosabiertos_deceyec_conteoscensales2012_nl.csv': PosixPath('/home/david/Documents/Repositories/academica/Votacion2026/data/Censos/DatosAbiertos_DECEyEC_ConteosCensales2012/DatosAbiertos_DECEyEC_ConteosCensales2012/datosabiertos_deceyec_conteoscensales2012_nl.csv'),
 'datosabiertos_deceyec_conteoscensales2012_oax.csv': PosixPath('/home/david/Documents/Repositories/academica/Votacion2026/data/Censos/DatosAbiertos_DECEyEC_ConteosCensales2012/DatosAbiertos_DECEyEC_ConteosCensales2012/datosabiertos_deceyec_conteoscensales2012_oax.csv'),
 'datosabiertos_deceyec_conteoscensales2012_pue.csv': PosixPath('/home/david/Documents/Repositories/academica/Votacion2026/data/Censos/DatosAbiertos_DECEyEC_ConteosCensales2012/DatosAbiertos_DECEyEC_ConteosCensales2012/datosabiertos_deceyec_conteoscensales2012_pue.csv'),
 'datosabiertos_deceyec_conteoscensales2012_qro.csv': PosixPath('/home/david/Documents/Repositories/academica/Votacion2026/data/Censos/DatosAbiertos_DECEyEC_ConteosCensales2012/DatosAbiertos_DECEyEC_ConteosCensales2012/datosabiertos_deceyec_conteoscensales2012_qro.csv'),
 'datosabiertos_deceyec_conteoscensales2012_qroo.csv': PosixPath('/home/david/Documents/Repositories/academica/Votacion2026/data/Censos/DatosAbiertos_DECEyEC_ConteosCensales2012/DatosAbiertos_DECEyEC_ConteosCensales2012/datosabiertos_deceyec_conteoscensales2012_qroo.csv'),
 'datosabiertos_deceyec_conteoscensales2012_sin.csv': PosixPath('/home/david/Documents/Repositories/academica/Votacion2026/data/Censos/DatosAbiertos_DECEyEC_ConteosCensales2012/DatosAbiertos_DECEyEC_ConteosCensales2012/datosabiertos_deceyec_conteoscensales2012_sin.csv'),
 'datosabiertos_deceyec_conteoscensales2012_slp.csv': PosixPath('/home/david/Documents/Repositories/academica/Votacion2026/data/Censos/DatosAbiertos_DECEyEC_ConteosCensales2012/DatosAbiertos_DECEyEC_ConteosCensales2012/datosabiertos_deceyec_conteoscensales2012_slp.csv'),
 'datosabiertos_deceyec_conteoscensales2012_son.csv': PosixPath('/home/david/Documents/Repositories/academica/Votacion2026/data/Censos/DatosAbiertos_DECEyEC_ConteosCensales2012/DatosAbiertos_DECEyEC_ConteosCensales2012/datosabiertos_deceyec_conteoscensales2012_son.csv'),
 'datosabiertos_deceyec_conteoscensales2012_tab.csv': PosixPath('/home/david/Documents/Repositories/academica/Votacion2026/data/Censos/DatosAbiertos_DECEyEC_ConteosCensales2012/DatosAbiertos_DECEyEC_ConteosCensales2012/datosabiertos_deceyec_conteoscensales2012_tab.csv'),
 'datosabiertos_deceyec_conteoscensales2012_tamps.csv': PosixPath('/home/david/Documents/Repositories/academica/Votacion2026/data/Censos/DatosAbiertos_DECEyEC_ConteosCensales2012/DatosAbiertos_DECEyEC_ConteosCensales2012/datosabiertos_deceyec_conteoscensales2012_tamps.csv'),
 'datosabiertos_deceyec_conteoscensales2012_tlax.csv': PosixPath('/home/david/Documents/Repositories/academica/Votacion2026/data/Censos/DatosAbiertos_DECEyEC_ConteosCensales2012/DatosAbiertos_DECEyEC_ConteosCensales2012/datosabiertos_deceyec_conteoscensales2012_tlax.csv'),
 'datosabiertos_deceyec_conteoscensales2012_ver.csv': PosixPath('/home/david/Documents/Repositories/academica/Votacion2026/data/Censos/DatosAbiertos_DECEyEC_ConteosCensales2012/DatosAbiertos_DECEyEC_ConteosCensales2012/datosabiertos_deceyec_conteoscensales2012_ver.csv'),
 'datosabiertos_deceyec_conteoscensales2012_yuc.csv': PosixPath('/home/david/Documents/Repositories/academica/Votacion2026/data/Censos/DatosAbiertos_DECEyEC_ConteosCensales2012/DatosAbiertos_DECEyEC_ConteosCensales2012/datosabiertos_deceyec_conteoscensales2012_yuc.csv'),
 'datosabiertos_deceyec_conteoscensales2012_zac.csv': PosixPath('/home/david/Documents/Repositories/academica/Votacion2026/data/Censos/DatosAbiertos_DECEyEC_ConteosCensales2012/DatosAbiertos_DECEyEC_ConteosCensales2012/datosabiertos_deceyec_conteoscensales2012_zac.csv'),
 '01_descripcioncampos_conteoscensales2015.txt': PosixPath('/home/david/Documents/Repositories/academica/Votacion2026/data/Censos/DatosAbiertos_DECEyEC_ConteosCensales2015/DatosAbiertos_DECEyEC_ConteosCensales2015/01_descripcioncampos_conteoscensales2015.txt'),
 'datosabiertos_deceyec_conteoscensales2015_ags.csv': PosixPath('/home/david/Documents/Repositories/academica/Votacion2026/data/Censos/DatosAbiertos_DECEyEC_ConteosCensales2015/DatosAbiertos_DECEyEC_ConteosCensales2015/datosabiertos_deceyec_conteoscensales2015_ags.csv'),

Vemoos una mezcla de archivos .txt y .csv. Entonces, vamos a estructurarlos para un mejor analisis.

In [3]:
txt_files = [f for f in files.keys() if f.endswith(".txt")]
txt_files

['01_descripcioncampos_conteoscensales_prisionpreventiva2024.txt',
 '01_descripcioncampos_conteoscensales_votoanticipado2024.txt',
 '01_descripcioncampos_conteoscensales2009.txt',
 '01_descripcioncampos_conteoscensales2012.txt',
 '01_descripcioncampos_conteoscensales2015.txt',
 '01_descripcioncampos_conteoscensales2018.txt',
 '01_descripcioncampos_conteoscensales2021.txt',
 '01_descripcioncampos_conteoscensales2024.txt']

## Diccionario de datos.

Notemos que los archivos .txt corresponden a los diccionarios de datos. Entonces debemos extraer la información relevante.

In [ ]:
d0 = files[txt_files[-1]]

with open(d0, "r") as dic:
    text = dic.read()

codebook = text.split("\n")
vart = {}
adinfo = {}
k = 0
for c in codebook:
    line = c.split("\t")
    if len(line) == 2:
        if line[0] != "":
            vart[line[0]] = line[1]
        else:
            adinfo[k] = line[1]
    k+=1
# Extraemos las variables relevantes
vart

{'AELEC': 'Año de elección (2009,2012,2015, 2018, 2021 y 2024)',
 'FELECCION': 'Fecha de la jornada electoral (formato corto)',
 'EDOCVE': 'Clave INE de entidad federativa',
 'EDONOM': 'Nombre de la entidad federativa',
 'MPIOCVE': 'Clave INE de Municipio',
 'MPIONOM': 'Nombre del municipio',
 'SECCION': 'Sección electoral en el año correspondiente',
 'TIPOSEC': 'Tipo de sección en el año correspondiente (U Urbana; M Mixta; R Rural)',
 'DEF': 'Distrito Electoral Federal en el marco cartográfico de la DERFE 2023',
 'SEXO': 'Sexo de las personas (0 Hombres; 1 Mujeres; 2 No binario)',
 'EDAD': 'Años de edad cumplidos al día de la elección de las personas',
 'LN': 'Lista nominal de los cuadernillos para todas las casillas catalogadas',
 'SV': 'Registros con marca de voto.',
 'NV': 'Registros sin marca de voto.',
 'NS': 'Registros no especificados en participación, pues corresponden a:',
 '01': 'AGUASCALIENTES',
 '02': 'BAJA CALIFORNIA',
 '03': 'BAJA CALIFORNIA SUR',
 '04': 'CAMPECHE',
 '05': 'COAHUILA',
 '06': 'COLIMA',
 '07': 'CHIAPAS',
 '08': 'CHIHUAHUA',
 '09': 'CIUDAD DE MÉXICO (DISTRITO FEDERAL antes de 2015)',
 '10': 'DURANGO',
 '11': 'GUANAJUATO',
 '12': 'GUERRERO',
 '13': 'HIDALGO',
 '14': 'JALISCO',
 '15': 'ESTADO DE MÉXICO',
 '16': 'MICHOACÁN',
 '17': 'MORELOS',
 '18': 'NAYARIT',
 '19': 'NUEVO LEON',
 '20': 'OAXACA',
 '21': 'PUEBLA',
 '22': 'QUERETARO',
 '23': 'QUINTANA ROO',
 '24': 'SAN LUIS POTOSI',
 '25': 'SINALOA',
 '26': 'SONORA',
 '27': 'TABASCO',
 '28': 'TAMAULIPAS',
 '29': 'TLAXCALA',
 '30': 'VERACRUZ',
 '31': 'YUCATAN',
 '32': 'ZACATECAS'}

In [12]:
adinfo

{17: '- Registro correspondiente a un cuadernillo sin marcas de votación.',
 18: '- Registro correspondiente a un cuadernillo no disponible para su captura.',
 19: '- Registro correspondiente a una página no disponible en el cuadernillo.'}

Notemos que adinfo extrajo los motivos del valor NS. Sin emabargo, esto no es relevante para nuestro analisis. Entonces extraeremos los codigos relevantes.

In [18]:
states= {}
codes = {}
for k, v in vart.items():
    try:
        int(k)
        states[k] = v
    except:
        codes[k] = v

states

{'01': 'AGUASCALIENTES',
 '02': 'BAJA CALIFORNIA',
 '03': 'BAJA CALIFORNIA SUR',
 '04': 'CAMPECHE',
 '05': 'COAHUILA',
 '06': 'COLIMA',
 '07': 'CHIAPAS',
 '08': 'CHIHUAHUA',
 '09': 'CIUDAD DE MÉXICO (DISTRITO FEDERAL antes de 2015)',
 '10': 'DURANGO',
 '11': 'GUANAJUATO',
 '12': 'GUERRERO',
 '13': 'HIDALGO',
 '14': 'JALISCO',
 '15': 'ESTADO DE MÉXICO',
 '16': 'MICHOACÁN',
 '17': 'MORELOS',
 '18': 'NAYARIT',
 '19': 'NUEVO LEON',
 '20': 'OAXACA',
 '21': 'PUEBLA',
 '22': 'QUERETARO',
 '23': 'QUINTANA ROO',
 '24': 'SAN LUIS POTOSI',
 '25': 'SINALOA',
 '26': 'SONORA',
 '27': 'TABASCO',
 '28': 'TAMAULIPAS',
 '29': 'TLAXCALA',
 '30': 'VERACRUZ',
 '31': 'YUCATAN',
 '32': 'ZACATECAS'}

In [17]:
codes

{'AELEC': 'Año de elección (2009,2012,2015, 2018, 2021 y 2024)',
 'FELECCION': 'Fecha de la jornada electoral (formato corto)',
 'EDOCVE': 'Clave INE de entidad federativa',
 'EDONOM': 'Nombre de la entidad federativa',
 'MPIOCVE': 'Clave INE de Municipio',
 'MPIONOM': 'Nombre del municipio',
 'SECCION': 'Sección electoral en el año correspondiente',
 'TIPOSEC': 'Tipo de sección en el año correspondiente (U Urbana; M Mixta; R Rural)',
 'DEF': 'Distrito Electoral Federal en el marco cartográfico de la DERFE 2023',
 'SEXO': 'Sexo de las personas (0 Hombres; 1 Mujeres; 2 No binario)',
 'EDAD': 'Años de edad cumplidos al día de la elección de las personas',
 'LN': 'Lista nominal de los cuadernillos para todas las casillas catalogadas',
 'SV': 'Registros con marca de voto.',
 'NV': 'Registros sin marca de voto.',
 'NS': 'Registros no especificados en participación, pues corresponden a:'}

### Conglomerado

Finalmente haremos un conglomerado del diccionario de datos. Extrayendo la información de los estados y las variables.

In [32]:
import pandas as pd

datadict = pd.DataFrame(index = codes.keys(),
                        data= codes.values(),
                        columns=['Descripción'])

mexico = pd.DataFrame(index= states.keys(),
                        data=states.values(),
                        columns=["Descripción"])
display(datadict)
mexico

                                                 Descripción
AELEC      Año de elección (2009,2012,2015, 2018, 2021 y ...
FELECCION      Fecha de la jornada electoral (formato corto)
EDOCVE                       Clave INE de entidad federativa
EDONOM                       Nombre de la entidad federativa
MPIOCVE                               Clave INE de Municipio
MPIONOM                                 Nombre del municipio
SECCION          Sección electoral en el año correspondiente
TIPOSEC    Tipo de sección en el año correspondiente (U U...
DEF        Distrito Electoral Federal en el marco cartogr...
SEXO       Sexo de las personas (0 Hombres; 1 Mujeres; 2 ...
EDAD       Años de edad cumplidos al día de la elección d...
LN         Lista nominal de los cuadernillos para todas l...
SV                              Registros con marca de voto.
NV                              Registros sin marca de voto.
NS         Registros no especificados en participación, p...

                                          Descripción
01                                     AGUASCALIENTES
02                                    BAJA CALIFORNIA
03                                BAJA CALIFORNIA SUR
04                                           CAMPECHE
05                                           COAHUILA
06                                             COLIMA
07                                            CHIAPAS
08                                          CHIHUAHUA
09  CIUDAD DE MÉXICO (DISTRITO FEDERAL antes de 2015)
10                                            DURANGO
11                                         GUANAJUATO
12                                           GUERRERO
13                                            HIDALGO
14                                            JALISCO
15                                   ESTADO DE MÉXICO
16                                          MICHOACÁN
17                                            MORELOS
18                                            NAYARIT
19                                         NUEVO LEON
20                                             OAXACA
21                                             PUEBLA
22                                          QUERETARO
23                                       QUINTANA ROO
24                                    SAN LUIS POTOSI
25                                            SINALOA
26                                             SONORA
27                                            TABASCO
28                                         TAMAULIPAS
29                                           TLAXCALA
30                                           VERACRUZ
31                                            YUCATAN
32                                          ZACATECAS

Finalmente, haremos el conjunto de datos por archivo

In [77]:

def codebook(file):
    with open(file, "r") as dic:
        text = dic.read()

    codebook = text.split("\n")
    vart = {}
    adinfo = {}
    k = 0
    for c in codebook:
        line = c.split("\t")
        if len(line) == 2:
            if line[0] != "":
                vart[line[0]] = line[1]
            else:
                adinfo[k] = line[1]
        k+=1
    
    states= {}
    codes = {}
    for k, v in vart.items():
        try:
            int(k)
            states[k] = v
        except:
            codes[k] = v

    datadict = pd.DataFrame(index = codes.keys(),
                        data= codes.values(),
                        columns=['Descripción'])

    mexico = pd.DataFrame(index= states.keys(),
                            data=states.values(),
                            columns=["Descripción"])
    return datadict, mexico, adinfo

import json

for f in txt_files:
    codes, maps, adinfo = codebook(files[f])
    name = f.split("_")[-1][:-4]
    codes.to_csv(CENSO_DATA / f"code_{name}.csv")
    maps.to_csv(CENSO_DATA / f"states_{name}.csv")
    if len(adinfo) > 0:
        print(adinfo)
        with open(CENSO_DATA / f"info_{name}.json", "w") as info:
           json.dump(adinfo, info)

{17: '- Registro correspondiente a un cuadernillo sin marcas de votación.', 18: '- Registro correspondiente a un cuadernillo no disponible para su captura.', 19: '- Registro correspondiente a un cuadernillo solicitado por autoridad jurisdiccional.', 20: '- Registro correspondiente a una página no disponible en el cuadernillo'}
{17: '- Registro correspondiente a un cuadernillo sin marcas de votación.', 18: '- Registro correspondiente a un cuadernillo no disponible para su captura.', 19: '- Registro correspondiente a un cuadernillo solicitado por autoridad jurisdiccional.', 20: '- Registro correspondiente a una página no disponible en el cuadernillo'}
{17: '- Registro correspondiente a un cuadernillo sin marcas de votación.', 18: '- Registro correspondiente a un cuadernillo no disponible para su captura.', 19: '- Registro correspondiente a un cuadernillo solicitado por autoridad jurisdiccional.', 20: '- Registro correspondiente a una página no disponible en el cuadernillo'}
{17: '- Registro correspondiente a un cuadernillo sin marcas de votación.', 18: '- Registro correspondiente a un cuadernillo no disponible para su captura.', 19: '- Registro correspondiente a un cuadernillo solicitado por autoridad jurisdiccional.', 20: '- Registro correspondiente a una página no disponible en el cuadernillo'}
{17: '- Registro correspondiente a un cuadernillo sin marcas de votación.', 18: '- Registro correspondiente a un cuadernillo no disponible para su captura.', 19: '- Registro correspondiente a un cuadernillo solicitado por autoridad jurisdiccional.', 20: '- Registro correspondiente a una página no disponible en el cuadernillo'}
{17: '- Registro correspondiente a un cuadernillo sin marcas de votación.', 18: '- Registro correspondiente a un cuadernillo no disponible para su captura.', 19: '- Registro correspondiente a una página no disponible en el cuadernillo.'}